export const cardItems = [
  {
    id: 1,
    image: '../../assets/img/food01.jpg',
    title: 'food 1',
    description: 'text description 1',
  },
  {
    id: 2,
    image: '../../assets/img/food02.jpg',
    title: 'food 2',
    description: 'text description 2',
  },
  {
    id: 3,
    image: '../../assets/img/food03.jpg',
    title: 'food 3',
    description: 'text description 3',
  },
  {
    id: 4,
    image: '../../assets/img/food04.jpg',
    title: 'food 4',
    description: 'text description 4',
  },
  {
    id: 5,
    image: '../../assets/img/food05.jpg',
    title: 'food 5',
    description: 'text description 5',
  },
  {
    id: 6,
    image: '../../assets/img/food06.jpg',
    title: 'food 6',
    description: 'text description 6',
  },
  {
    id: 7,
    image: '../../assets/img/food07.jpg',
    title: 'food 7',
    description: 'text description 7',
  },
  {
    id: 8,
    image: '../../assets/img/food08.jpg',
    title: 'food 8',
    description: 'text description 8',
  },
  {
    id: 9,
    image: '../../assets/img/food09.jpg',
    title: 'food 9',
    description: 'text description 9',
  },
  {
    id: 10,
    image: '../../assets/img/food10.jpg',
    title: 'food 10',
    description: 'text description 10',
  },
  {
    id: 11,
    image: '../../assets/img/food11.jpg',
    title: 'food 11',
    description: 'text description 11',
  },
  {
    id: 12,
    image: '../../assets/img/food12.jpg',
    title: 'food 12',
    description: 'text description 12',
  },
  {
    id: 13,
    image: '../../assets/img/food13.jpg',
    title: 'food 13',
    description: 'text description 13',
  },
  {
    id: 14,
    image: '../../assets/img/food14.jpg',
    title: 'food 14',
    description: 'text description 14',
  },
  {
    id: 15,
    image: '../../assets/img/food15.jpg',
    title: 'food 15',
    description: 'text description 15',
  },
  {
    id: 16,
    image: '../../assets/img/food16.jpg',
    title: 'food 16',
    description: 'text description 16',
  },
  {
    id: 17,
    image: '../../assets/img/food17.jpg',
    title: 'food 17',
    description: 'text description 17',
  },
  {
    id: 18,
    image: '../../assets/img/food18.jpg',
    title: 'food 18',
    description: 'text description 18',
  },
  {
    id: 19,
    image: '../../assets/img/food19.jpg',
    title: 'food 19',
    description: 'text description 19',
  },
  {
    id: 20,
    image: '../../assets/img/food20.jpg',
    title: 'food 20',
    description: 'text description 20',
  },
  {
    id: 21,
    image: '../../assets/img/food21.jpg',
    title: 'food 21',
    description: 'text description 21',
  },
  {
    id: 22,
    image: '../../assets/img/food22.jpg',
    title: 'food 22',
    description: 'text description 22',
  },
  {
    id: 23,
    image: '../../assets/img/food23.jpg',
    title: 'food 23',
    description: 'text description 23',
  },
  {
    id: 24,
    image: '../../assets/img/food24.jpg',
    title: 'food 24',
    description: 'text description 24',
  },
  {
    id: 25,
    image: '../../assets/img/food25.jpg',
    title: 'food 25',
    description: 'text description 25',
  },
  {
    id: 26,
    image: '../../assets/img/food26.jpg',
    title: 'food 26',
    description: 'text description 26',
  },
  {
    id: 27,
    image: '../../assets/img/food27.jpg',
    title: 'food 27',
    description: 'text description 27',
  },
  {
    id: 28,
    image: '../../assets/img/food28.jpg',
    title: 'food 28',
    description: 'text description 28',
  },
  {
    id: 29,
    image: '../../assets/img/food29.jpg',
    title: 'food 29',
    description: 'text description 29',
  },
  {
    id: 30,
    image: '../../assets/img/food30.jpg',
    title: 'food 30',
    description: 'text description 30',
  },
  {
    id: 31,
    image: '../../assets/img/food31.jpg',
    title: 'food 31',
    description: 'text description 31',
  },
  {
    id: 32,
    image: '../../assets/img/food32.jpg',
    title: 'food 32',
    description: 'text description 32',
  },
  {
    id: 33,
    image: '../../assets/img/food33.jpg',
    title: 'food 33',
    description: 'text description 33',
  },
];
